name: my-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - python-dateutil
  - pytz
  - openpyxl
  - jupyterlab=3.6.5  # ← КЛЮЧЕВАЯ СТРОКА! Фиксируем стабильную 3.x
